apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: task-manager
type: Opaque
data:
  # These are base64 encoded values — paste YOUR output from the commands above
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_USER: dGFza3VzZXI=
  MYSQL_PASSWORD: dGFza3Bhc3N3b3Jk
  MYSQL_DATABASE: dGFza2Ri